version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: uvicorn main:app --host 0.0.0.0 --reload --lifespan on --port 8000
    volumes:
      - ./app:/app
    environment:
      - HF_TOKEN=${HF_TOKEN}
    ports:
      - 8000:8000
    env_file:
      - .env