version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --reload --lifespan on
    volumes:
      - ./app:/app
    environment:
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
    ports:
      - 8000:8000
    env_file:
      - .env